name: Skywars
main: net.omniblock.skywars.Skywars
softdepend: [OmniNetwork, WorldEdit, Citizens]
version: 12.0.2
commands:
   lobby:
      description: Comando alias para salir al lobby.
      usage: /<command>
   salir:
      description: Comando alias para salir al lobby.
      usage: /<command>
   leave:
      description: Comando alias para salir al lobby.
      usage: /<command>
   hub:
      description: Comando alias para salir al lobby.
      usage: /<command>
   gen_command_vote:
      description: Comando generado para la inicialización de votos.
      usage: /<command>
   gen_command_test:
      description: Comando generado para iniciar testeos.
      usage: /<command>